# Monitoring
import os

NOME_API = "API"

APM_SERVER_URL = os.getenv("APM_SERVER_URL")
APM_SERVER_PORT = os.getenv("APM_SERVER_PORT")
APM_SERVICE_NAME = os.getenv("APM_SERVICE_NAME")
APM_SERVICE_URL = 'http://{}:{}'.format(APM_SERVER_URL, APM_SERVER_PORT)

SERVER_WORKER = os.getenv("SERVER_WORKER")
SERVER_LOG = os.getenv("SERVER_LOG")
SERVER_TIMEOUT = os.getenv("SERVER_TIMEOUT")
DATABASE_HOST = os.getenv("DATABASE_HOST")
DATABASE_PORT = os.getenv("DATABASE_PORT")
DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
DATABASE_NAME = os.getenv("DATABASE_NAME")
DATABASE_SCHEMA = os.getenv("DATABASE_SCHEMA")
DATABASE_LOG = os.getenv("DATABASE_LOG")
DATABASE_URL = 'postgresql://{}:{}@{}:{}/{}'.format(DATABASE_USER, DATABASE_PASSWORD, DATABASE_HOST, DATABASE_PORT, DATABASE_NAME)

ELASTICSEARCH_HOSTS = os.getenv("ELASTICSEARCH_HOSTS")
ELASTICSEARCH_PORT = os.getenv("ELASTICSEARCH_PORT")
ELASTICSEARCH_URL = 'http://{}:{}'.format(ELASTICSEARCH_HOSTS, ELASTICSEARCH_PORT)

ENVIROMENT = os.getenv("ENVIROMENT")
